Bump to @vercel/ncc@v0.34.0
Fixes "Error: error:0308010C:digital envelope routines::unsupported"
as Debian's nodejs v16.15.0 is already compiled with OpenSSL 3.

See https://github.com/vercel/ncc/issues/805

The full error log is as follows:

> ncc build ./src/index.ts -o lib --minify

ncc: Version 0.27.0
ncc: Compiling file index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at hashOf (/home/foka/OpenDRR/actions-gh-pages/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:3253134)
    at ncc (/home/foka/OpenDRR/actions-gh-pages/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:3256648)
    at runCmd (/home/foka/OpenDRR/actions-gh-pages/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:51537)
    at Object.819 (/home/foka/OpenDRR/actions-gh-pages/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:48344)
    at __webpack_require__ (/home/foka/OpenDRR/actions-gh-pages/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55043)
    at /home/foka/OpenDRR/actions-gh-pages/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55194
    at /home/foka/OpenDRR/actions-gh-pages/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55220
    at Object.<anonymous> (/home/foka/OpenDRR/actions-gh-pages/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}